### ISSUE TITLE
Awsome tool but gives panic run time error

### ISSUE THREAD

**Issue by MR-pentestGuy** [Tanmay-N/CORS-Scanner#1]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x656d0f]

**Comment by Tanmay-N** [comment]
Hi @MR-pentestGuy, Thank you for the report. Could you please share screenshot of this error? It will help us to investigate further for a fix.

**Comment by MR-pentestGuy** [comment]
![Uploading CORS.png…]()

**Comment by MR-pentestGuy** [comment]
[
![CORS](https://user-images.githubusercontent.com/71591447/102861497-c7cde300-4455-11eb-8364-1eb1890ee75c.png)
](url)

**Comment by MR-pentestGuy** [comment]
here the gau.txt i just named them as gau but actually they contains live subdomains

**Comment by Tanmay-N** [comment]
Hi @MR-pentestGuy, This error is due to empty response from one of your server and also our code was not handling error properly.  I made some changes in code please check once. Thanks again!

**Comment by MR-pentestGuy** [comment]
thank you
